aplicaciones/acceso/urls.py
from django.urls import path
from .views import *
from .api_views import *


app_name = 'acceso'

urlpatterns = [
    path('', Prueba.as_view(), name="prueba"),
    path('entradas/empleado/', EntradaEmpleadoView.as_view(), name="entrada_empleado"),
    #path('api/accesos/empleado', EntradaSalidaEmpCreateApiView.as_view()),    
    path('entradas/empleado_vehiculo/', EntradaEmpleadoVehiculoView.as_view(), name="entrada_empleado_vehiculo")
]

sigbanconfig/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.acceso.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/body.html
{% extends 'head.html' %}
{% load static %}
{% block body %}
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
    <div class="wrapper">
        <!-- Este es el header -->
        {% include 'header.html' %}        
        <!-- Este es el sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <!-- Esto es el breadcrum -->
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{title}}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item "><a href="{{request.path}}">{{request.path}}</a></li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div><!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    {% block content %}
                    
                    {% endblock content %}
                </div>
            </section>
        </div>  
                
        <!-- Footer -->
        {% include 'footer.html' %}    
    
    </div>
    <!-- ./wrapper -->
   
    
    <!-- jQuery -->
    <script src="{% static 'lib/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'lib/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
    $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    
    <!-- Sparkline -->
    <script src="{% static 'lib/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    
    <!-- jQuery Knob Chart -->
    
    <!-- daterangepicker -->
    <script src="{% static 'lib/plugins/moment/moment.min.js' %}"></script>
    
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'lib/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    
    <!-- overlayScrollbars -->
    <script src="{% static 'lib/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'lib/dist/js/pages/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'lib/dist/js/demo.js' %}"></script>
    
    
    {% block javascript %}
        
    {% endblock javascript %}
    
</body>
{% endblock body %}
    

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center text-dark text-sm">
    <strong id="fecha"></strong> Todos los derechos reservados.    
</footer>

<script>
    var anio = new Date().getFullYear();
    document.getElementById('fecha').innerHTML="Copyright &copy; " + anio + " SigBan";
</script>

templates/head.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{title}} | SigBan</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'lib/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'lib/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'lib/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    
    <!-- summernote -->
    
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">    
    
    <!-- Mis estilos -->
    <link rel="stylesheet" href="{% static 'lib/dist/css/mystyles.css' %}">

    {% block head %}
    {% endblock head %}
</head>

{% block body %}
    
{% endblock body %}
    
</html>

templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white  navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'acceso:prueba' %}" class="nav-link">Inicio</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-users-cog"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <span class="dropdown-header" style="font-size: 12px;">
                  Sú último acceso fue {{ request.user.last_login }}
              </span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
              <i class="fas fa-edit mr-2"></i> Editar perfil
          </a>                
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">
              <p>Este sistema te permitirá realizar diferentes actividades</p>
          </a>
      </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-power-off" aria-hidden="true"></i>
        </a>
    </li>           
  </ul>
</nav>
<!-- /.navbar -->

<!--Modal para confirmar la salida-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">¿Cerrar Sesión para <mark> {{ user.username}} </mark>?</h5>
      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
      </button>
      </div>
      <div class="modal-body">Al dar click en el botón Salir, cerrará la sesión para <mark> {{ user.username}} </mark>  </div>
      <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
      <a class="btn btn-primary" href="#">Salir</a>
      </div>
  </div>
  </div>
</div><!-- /.modal -->

<script>
  /* Script para abrir el modal de confirmar la salida */
  function abrir_modal(url)
        {
            $("#popup").load(url, function(){
                $(this).modal({
                    backdrop:'static',
                    keyboard: false
                })
                $(this).modal('show');
            });
            return false;
        } 
  /* Fin Script de modal de confirmación dde salida */  

</script>

templates/list.html
{% extends 'body.html' %}

{% block head %}
    <link rel="stylesheet" href="{% static 'lib/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"/><!-- Listo -->
    <link rel="stylesheet" href="{% static 'lib/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"/> <!-- Listo -->
    <script src="{% static 'lib/plugins/datatables/jquery.dataTables.min.js' %}"></script><!-- Listo -->
    <script src="{% static 'lib/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script><!-- Listo -->
    <script src="{% static 'lib/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script><!-- Listo -->
    <script src="{% static 'lib/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script><!-- Listo -->

{% endblock head %}


{% block content %}       
<div class="card card-info card-outline">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-search"></i>
            {{ title }}
        </h3>
    </div>
    <div class="card-body ">
        <table class="animated fadeIn fast  table table-sm table-bordered table-striped table-hover" id="data">
            <thead class="animated fadeIn">
            {% block columns %}

            {% endblock columns %}
            </thead>
            <tbody>
            {% block rows %}

            {% endblock rows %}
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        {% block buttons_list %}                                             
            <a id="btnA" class="btn btn-primary animated fadeIn btnAdd">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>            
            <a class="btn btn-success animated fadeIn" id="actualizar">
                <i class="fas fa-sync"></i> Actualizar
            </a>
        {% endblock buttons_list %}
    </div>
</div>
{% endblock content %}


{% block javascript %}

<script>
$(document).ready(function(){    
    $('#data').DataTable({
        responsive : true,
        autoWidth : true
    });
});
</script>    
{% endblock javascript %}
    

templates/sidebar.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{% static 'lib/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">SigBan</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% static 'lib/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">Usuario logueado</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->               
        
        <!-- Entrada y salida -->
        <li class="nav-item has-treeview ">
          <a href="#" class="nav-link {% if request.path == '/entradas/empleado/' %} active {% endif %}">
            <i class="far fa-address-book"></i>
            <p>
              Entradas/Salidas
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'acceso:entrada_empleado' %}" class="nav-link {% if request.path == '/entradas/empleado/' %} active {% endif %} ">
                <i class="far fa-id-badge"></i>
                <p>Empleado</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link {% if request.path == '/entradas/visitante/' %} active {% endif %}">
                <i class="far fa-user-circle"></i>
                <p>Visitante</p>
              </a>
            </li>   
            <li class="nav-item">
              <a href="" class="nav-link {% if request.path == '/entrada_salida/listado/accesos/' %} active {% endif %}">
                <i class="fas fa-list-ol"></i>
                <p>Listado de accesos</p>
              </a>
            </li>                      
            <li class="nav-item">
              <a href="" class="nav-link {% if request.path == '/entrada_salida/listado/salidas/' %} active {% endif %}">
                <i class="fas fa-list-ol"></i>
                <p>Listado de salidas</p>
              </a>
            </li>                      
          </ul>
        </li><!-- /.Entrada y salida -->

        <!-- Gestion de empleados -->
        <li class="nav-item has-treeview ">
          <a href="#" class="nav-link {% if request.path == '/entradas/empleado/' %} active {% endif %}">
            <i class="far fa-address-book"></i>
            <p>
              Gestion de empleados
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
                               
          </ul>
        </li><!-- /.Gestion de empleados -->

      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>